version: "3.8"

services: 
    backend:
        restart: always
        build: 
            context: .
            target: dev
        volumes: 
            - .:/app
        command: npm run dev
        ports: 
            - 3001:3000
        environment: 
            NODE_ENV: development